#2 double check log in
YuliiaRublenko/group-10-project pull request #21
Opened 2021-08-06 15:11 UTC by AleksPet

All is done

2021-08-06 15:12 UTC, Taran522 approved these changes
It looks much better this time. Ready for approval.

2021-08-06 15:19 UTC, YuliiaRublenko requested changes
change package name plz(it should always start with lower case)

2021-08-06 15:26 UTC, YuliiaRublenko approved these changes

2021-08-11 14:17 UTC, YuliiaRublenko commented
good code

2021-08-11 14:20 UTC, closed without merging